// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVIbuDLTEpRTzsMkpu-64ohLBZ99yh4P4',
    appId: '1:672200497005:web:421b631276ab6d34ee6c64',
    messagingSenderId: '672200497005',
    projectId: 'myapp-604c7',
    authDomain: 'myapp-604c7.firebaseapp.com',
    storageBucket: 'myapp-604c7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVZSrkvXDQIO9yYUyReWzP95ss8450qFk',
    appId: '1:672200497005:android:74bba58d4d62771cee6c64',
    messagingSenderId: '672200497005',
    projectId: 'myapp-604c7',
    storageBucket: 'myapp-604c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUMCknbfi9Jep1dHv3rr5rEqnbHUwiBFk',
    appId: '1:672200497005:ios:7a858fd3ac77cd58ee6c64',
    messagingSenderId: '672200497005',
    projectId: 'myapp-604c7',
    storageBucket: 'myapp-604c7.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUMCknbfi9Jep1dHv3rr5rEqnbHUwiBFk',
    appId: '1:672200497005:ios:7a858fd3ac77cd58ee6c64',
    messagingSenderId: '672200497005',
    projectId: 'myapp-604c7',
    storageBucket: 'myapp-604c7.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVIbuDLTEpRTzsMkpu-64ohLBZ99yh4P4',
    appId: '1:672200497005:web:08e540142cdae63aee6c64',
    messagingSenderId: '672200497005',
    projectId: 'myapp-604c7',
    authDomain: 'myapp-604c7.firebaseapp.com',
    storageBucket: 'myapp-604c7.firebasestorage.app',
  );

}